files: 
  intro:
    loop: true
    src: music/intro.mp3
  cap1:
    loop: true
    src: music/cap1.mp3
  cap2:
    loop: true
    src: music/cap2.mp3
  cap3:
    loop: true
    src: music/cap3.mp3
  cap4:
    loop: true
    src: music/cap4.mp3
  cap5:
    loop: true
    src: music/cap5.mp3
  carmela:
    loop: true
    src: music/carmela.mp3
options:
  volume: 0.5
  musicFadeInTime: 0.5
  musicFadeInDelay: 0.5
  musicFadeOutTime: 0.5
audioTriggers: {}
